# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'templateRN' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for templateRN

  # Required by RNFirebase
  pod 'Firebase/Core'

  # [OPTIONAL PODS] - comment out pods for firebase products you won't be using.
  pod 'Firebase/AdMob'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/DynamicLinks'
  pod 'Firebase/Performance'
  pod 'Firebase/Firestore'
  pod 'Firebase/Messaging'
  pod 'Firebase/RemoteConfig'
  pod 'Firebase/Storage'
  
  pod 'Fabric', '~> 1.7.6'
  pod 'Crashlytics', '~> 3.10.1'
  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  pod 'RNFS', :path => '../node_modules/react-native-fs'

end
